import { Component } from '@angular/core';

function log(className) {
  console.log(className);
  return (...args) => {
    console.log("Arguments passed to this class's constructor are ", args)
    return new className(...args);
  }
}

class myClassProto {
  constructor(arg1, arg2) {
    console.log(arg1, arg2);
  }
}

const myClass = new myClassProto(5, 10);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})

export class AppComponent {
  str = 'Hello world!';

  constructor() {
    console.log("This statement was generated by the app component constructor", this.aSimpleMethod(5, 2));
  }

  aSimpleMethod(a, b) {
    return a*b;
  }

}
